spring:
  datasource:
    url: jdbc:mysql://localhost:3306/art_trading_platform
    username: root
    password: Csy.020812
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*.xml